mysite/blogapp/urls.py
from django.urls import include, path, re_path
from django.contrib import admin
from . import views

app_name = 'blogapp'
urlpatterns = [
	# project homepage, ex: /blog/
	path('', views.blogHome, name='blogHome'),
]

urlpatterns += [
	# page to create an account
	path('accounts/new_account/', views.CreateAccountView.as_view(), name='create_account'),
	re_path(r'^profile/$', views.UserProfileView.as_view(), name='user_profile'),
]

urlpatterns += [
	re_path(r'^posts$', views.getPosts, name='get_posts'),
	re_path(r'^authors$', views.getAuthors, name='get_authors'),
	path('post_list/', views.postList.as_view(), name='post_list'),
	path('create_post/', views.BlogPostCreate.as_view(), name='create_post'),
	path('post/<int:pk>/', views.PostDetail.as_view(), name='post_detail'),
	path('post/<int:pk>/edit/', views.BlogPostEdit.as_view(), name='edit_post'),
	path('post/<int:pk>/delete/', views.BlogPostDelete.as_view(), name='delete_post'),
	re_path(r'^filtered_posts$', views.FilterListView.as_view(), name='filter_list'),
]

mysite/mysite/urls.py
from django.contrib import admin
from django.urls import include, path
from blogapp import views
from django.views.generic import RedirectView

urlpatterns = [
	path('', views.blogHome, name='blogHome'),
	path('blogapp/', include('blogapp.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
	path('resume/',RedirectView.as_view(url='http://rebeccakempe.com/static/blog/Kempe_Resume_2018.pdf'))
  ]

mysite/blogapp/models.py
from django.db import models
from django.db.models.signals import post_save
from django.core.cache import cache
from django.contrib.auth.models import User
from django.urls import reverse_lazy, reverse

from django.utils import timezone

class Author(models.Model):
	user = models.ForeignKey(User, null=False, on_delete=models.CASCADE, editable=False)
	name = models.CharField(max_length=200)
	
	def __str__(self):
		return self.name
	
	def to_dict(self):
		return {
			'name': self.name,
		}

class BlogPost(models.Model):
	title = models.CharField(max_length=200)
	pub_date = models.DateField(auto_now_add=True)
	pub_time = models.TimeField(auto_now_add=True)
	last_edit_date = models.DateTimeField(auto_now=True)
	author = models.ForeignKey(Author, null=True, on_delete=models.SET_NULL, editable=False)
	content = models.TextField(null=True)
	
		
	def __str__(self):
		return self.title
	
	def get_absolute_url(self):
		return reverse('blogapp:blog/post_detail', kwargs={ 'pk' : self.pk })

	def to_dict(self):
		pub_time = str(self.pub_time)
		pub_date = str(self.pub_date)
		last_edit_date = str(self.last_edit_date)
		author = str(self.author)

		return {
			'id': self.id,
			'title': self.title,
			'pub_date': pub_date,
			'pub_time': pub_time,
			'last_edit_date': last_edit_date,
			'author': author,
			'content': self.content
		}
		
	class Meta:
		ordering = ['pub_date', 'pub_time']

mysite/blogapp/forms.py
from django import forms
from django.forms import ModelForm, widgets, Textarea

from blogapp.models import *

from django.contrib import messages
from django.core.exceptions import NON_FIELD_ERRORS
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm

from django.utils.translation import gettext_lazy as _


class CreateUserForm(UserCreationForm):
	email = forms.EmailField(required=True)
	
	class Meta:
		model = User
		fields = ('username','email','password1','password2')
		
	def save(self, commit=True):
		user = super(CreateUserForm, self).save(commit=False)
		user.email = self.cleaned_data['email']
		user.save()
		
		user_id = user.id
		author = Author.objects.create(user=user, name=user.username)
		
		return user
        	
class CreatePostForm(ModelForm):
	
	def __init__(self, *args, **kwargs):
		super(CreatePostForm, self).__init__(*args, **kwargs)
		self.fields['title'].widget.attrs = {
			'class': 'title_entry'
		}
		self.fields['content'].widget.attrs = {
			'class': 'post_content_entry'
		}
	
	class Meta:
		model = BlogPost
		fields = ('title','content')
		
	        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        

mysite/blogapp/views.py
# resources for browser navigation and webpage rendering
from django.http import HttpResponse, HttpResponseRedirect, JsonResponse
from django.shortcuts import render, get_object_or_404
from django.utils.html import escape
from django.urls import reverse_lazy, reverse

# views used in this file
from django.views import View
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.views.generic.detail import DetailView
from django.views.generic import ListView
from django.views.generic.base import TemplateView

# authentication and login resources
from django.contrib.auth import login, logout, authenticate
from django.contrib.auth.mixins import LoginRequiredMixin

# forms used in this file
from blogapp.forms import CreateUserForm, CreatePostForm

# models used in this file
from django.contrib.auth.models import User
from blogapp.models import *

import json




# INDEX  VIEW
# ===========

def blogHome(request):
	
	return render(
		request,
		'index.html',
		{
		}
	)

def getPosts(request):
	format = 'default'
	info_type = ''
	filter_string = None
	posts = []
	posts_json = []
	post_ids = []
	json_return = []
	new_posts = []
	no_new_posts = 0
	
	format = _clean(request, 'format', 'default')
	filter_string = _clean(request, 'filter')
	info_type = _clean(request, 'info_type')

	posts = BlogPost.objects.filter()
	
	if info_type == 'ids':
		for post in posts:
			post_ids.append(post.id)
		json_return = post_ids
	
	if info_type == 'update_ids':
		current_post_ids = request.GET.getlist('current_post_ids[]', [])
		current_post_ids = [json.loads(item) for item in current_post_ids]
		for post in posts:
			post_ids.append(post.id)
		if post_ids == current_post_ids:
			json_return = ['no new posts']
		else:
			for post in posts:
				if post.id not in current_post_ids:
					new_posts.append(post.to_dict())
					no_new_posts += 1
			json_return = no_new_posts
		
	return HttpResponse(
		json.dumps(json_return),
		content_type='application/json'
	 )

def getAuthors(request):
	format = 'default'
	filter_string = None
	authors = []
	authorslist = []
	
	format = _clean(request, 'format', 'default')
	filter_string = _clean(request, 'filter')
	
	authors = Author.objects.all()
		
	for author in authors:
		authorslist.append(
			[
				"<div><a href='javascript:filter(\"author\", " + str(author.id) + ", \"" + author.name + "\");'>" + author.name + "</a></div>"
			]
		)
	
	return HttpResponse(
		json.dumps(authorslist),
		content_type='application/json'
	 )

class postList(ListView):
	model = BlogPost
	template_name = 'blog/post_list.html'
	
	def get_queryset(self):
		qs = super().get_queryset()
		return BlogPost.objects.all().order_by('-pub_date', '-pub_time')
	
	def get_context_data(self, **kwargs):
		context = super().get_context_data(**kwargs)
		return context

class FilterListView(ListView):
	model = BlogPost
	template_name = 'blog/filter_list.html'
	format = 'default'
	filter_string = None
	filtered_posts = []
	
	def get_queryset(self):
		format = _clean(self.request, 'format', 'default')
		filter_string = _clean(self.request, 'filter')
		
		if filter_string:
			filters = filter_string.split(",")
			for f in filters:
				f_parts = f.split("_")
				if len(f_parts) == 2:
					filter_type = f_parts[0]
					filter_id = f_parts[1]
					if filter_type == "author":
						filtered_posts = BlogPost.objects.filter(author=filter_id)
# 						return BlogPost.objects.filter(author__username__contains=self.kwargs['author']).order_by('-pub_date')
		qs = super(FilterListView, self).get_queryset()
		return filtered_posts.order_by('-pub_date')


# USER ACCOUNT VIEWS
# ==================

class CreateAccountView(View):
	form_class = CreateUserForm
	initial = { 'key' : 'value'}
	template_name = 'registration/new_account.html'
	
	def get(self, request):
		form = self.form_class(initial=self.initial)
		if request.user.is_authenticated:
			#TODO Give user option to logout or return to profile
			return HttpResponse("You are already logged in.")
		return render(request, self.template_name, { 'form' : form })
	
	def post(self, request):
		form = self.form_class(request.POST)
		if form.is_valid():
			form.save()
			return HttpResponse('Account created. <a class="btn blue_btn" href="/accounts/login/">login</a>')
		else:
			return HttpResponse('An error has occurred. <a class="btn blue_btn" href="/blog/">Home</a>' )

class UserProfileView(LoginRequiredMixin, ListView):
	model = BlogPost
	template_name = 'profile.html'
	
	def get_queryset(self):
		qs = super(UserProfileView, self).get_queryset()
		user=self.request.user
		id = user.id
		return qs.filter(author__user=id).order_by('-pub_date')



# BLOG POST VIEWS
# ===============

class PostDetail(DetailView):
	model = BlogPost

class BlogPostCreate(LoginRequiredMixin, CreateView):
	template_name = 'blog/create_post.html'
	form_class = CreatePostForm
	initial = { 'key' : 'value'}
	
	def get(self, request):
		form = self.form_class(initial=self.initial)
		return render(request, self.template_name, { 'form' : form })
	
	def form_valid(self, form):
		author = Author.objects.get(user_id=self.request.user.id)
		form.instance.author = author
		return super().form_valid(form)
		if form.is_valid():
			form.save()

class BlogPostEdit(LoginRequiredMixin, UpdateView):
	model = BlogPost
	fields = ('title', 'content')
	template_name = 'edit_post.html'
	
	def get_queryset(self):
		qs = super(BlogPostEdit, self).get_queryset()
		return qs.filter(author=self.request.user)
		
	def form_valid(self, form):
		form.instance.last_edit_date = now
		return super().form_valid(form)
		if form.is_valid():
			form.save()
	
class BlogPostDelete(LoginRequiredMixin, DeleteView):
	model = BlogPost
	template_name = 'delete_post.html'
	
	def get_queryset(self):
		qs = super(BlogPostDelete, self).get_queryset()
		return qs.filter(author=self.request.user)
	success_url='/blog/'

def _clean(request, param, default='', method='GET'):
	clean_value = None

	if method == 'GET':
		clean_value = escape(request.GET.get(param, default))
	elif method == 'POST':
		clean_value = escape(request.POST.get(param, default))

	return clean_value
		
		
# RESUME VIEW
# =============


def resume(request):
	return HttpResponseRedirect("../blog/static/blog/Kempe_Resume_2018.pdf")
	
		
		
		
		
		
		
		

mysite/blogapp/templates/blog/author_detail.html
{% extends 'base.html' %}
{% load static %}
{% block nav %}
	<div class="navbar col-xs-12">
		<a href="{% url 'index' %}"><img class="home_arrow" alt="home" src="{% static 'blog/home_arrow.png' %}"></a>
		<a href=""> {% with blogpost_list.all|first as post %}
			{{ post.author }}
			{% endwith %} 
		</a>
		|
		<a href="{% url 'blog:create_post' %}"> + post</a>
	</div>
{% endblock %}

{% block content %}
{% csrf_token %}

<div id="post_detail">
	{% if blogpost_list %}
	{% for post in blogpost_list %} 
		<div class="post_container row">
			<div class="col-sm-2"></div>
			<div class="post_date_container col-sm-2">
		        <div class="post_title_equalizer"></div>
				<p class="post_date">{{ post.pub_date|date:"DATE_FORMAT" }}</p>
				<p class="edit_date">last edited: {{ post.last_edit_date }}</p>
	        </div>
	        <div class="post col-sm-6 col-lg-4">
		        <a href="{% url 'blog:post_detail' post.id %}" class="post_title">{{ post.title }}</a>
		        <div class="post_content">{{ post.content|linebreaks }}</div>
	        </div>
	        <div class="col-sm-2 col-lg-4"></div>
	    </div>
	    {% endfor %} 
    {% else %}
      <p class="container">This author hasn't written any posts yet.</p>
    {% endif %} 
	
</div>


{% endblock %}

mysite/blogapp/templates/blog/base_postModification.html
{% extends 'blog/blog_base.html' %}

{% load static %}
{% block nav %}
	<div class="navbar col-xs-12">
		<a href="{% url 'index' %}"><img class="home_arrow" alt="home" src=""></a>
		|
		<a href="{% url 'blogapp:create_post' %}"> + post</a>
	</div>
{% endblock %}
{% block content %}
	<div class="post_modification">
	{% block formPOST %}
		<form method="POST" action="">
			{% csrf_token %}
			{% block formContent %}
			{% endblock %}
		</form>
	{% endblock %}
	</div>
{% endblock %}

mysite/blogapp/templates/blog/blog_base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
	{% block title %}{% endblock %}
	
	<meta name="viewport" content="width=device-width, initial-scale=1">
	
	<!-- jQuery library -->
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
	<!-- bootstrap Libraries -->
	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
	
	<!-- scripts -->
	<script src="{% static 'blog/jquery.js' %}" type="text/javascript"></script>
	
	<!-- stylesheets -->
	<link rel="stylesheet" type="text/css" href="{% static 'blog/blog_style.css' %}" />
	
</head>
<body>
	
	{% block modals %}{% endblock %}
	
	<div class="container-fluid">
		{% block content %}{% endblock %}
	</div>
	
	<footer class="footer">
		<p><a href="#"></a></p>
	</footer>

	{% block javascript %}{% endblock %}
	
</body>
</html>

mysite/blogapp/templates/blog/blogpost_detail.html
{% extends "base.html" %}

{% block nav %}
{% load static %}
	<div class="navbar col-xs-12">
		<a href="{% url 'index' %}"><img class="home_arrow" alt="home" src="{% static 'blog/home_arrow.png' %}"></a>
		|
		<a href="{% url 'blogapp:create_post' %}"> + post</a>
	</div>
{% endblock %}

{% block content %}
{% csrf_token %}

<div class="container" id="post_detail">
	<div class="post_title"> {{ object.title }} </div>
	<div class="post_content"> {{ object.content|linebreaks }} </div>
	<div >author: <a href="{% url 'blogapp:author_profile' object.author %}" class="post_author"> {{ object.author }} </a></div> <!-- author detail link not yet defined -->
</div>

{% endblock %}

mysite/blogapp/templates/blog/create_post.html
{% extends 'blog/base_postModification.html' %}

{% block formContent%}
<div class="container">
	{{ form }}
	<input class="submit_btn blue_btn" type="submit" name="submit" value="CreatePost" />
</div>
{% endblock %}

mysite/blogapp/templates/blog/delete_post.html
{% extends 'base_postModification.html' %}

{% block formContent%}

<div class="container" id="post_delete">
	<div id="post_delete_dialogue">
		Are you sure you want to delete "{{ object }}"?
	</div>
	<input class="submit_btn blue_btn" type="submit" value="Delete" />

{% endblock %}

mysite/blogapp/templates/blog/edit_post.html
{% extends 'base_postModification.html' %}

{% block formContent %}
<div class="container" id="edit_post">
    {{ form }}
    <input class="submit_btn blue_btn" type="submit" name="submit" value="UpdatePost" />
</div>

{% endblock %}

mysite/blogapp/templates/blog/filter_list.html
{% csrf_token %}

{% if object_list %}
{% for post in object_list %}
<div class="post_container row">
	<div class="col-sm-2"></div>
	<div class="post_date_container col-sm-2">
		<div id="eqpost-{{ post.id }}" class="post_title_equalizer"></div>
		<p class="post_date">{{ post.pub_date|date:"DATE_FORMAT" }}</p>
	</div>
	<div class="post col-sm-6 col-lg-5">
		<a href="#" id="post-{{ post.id }}" class="post_title">{{ post.title }}</a>
		<div class="post_content">{{ post.content|linebreaks }}</div>
		<p>author: {{ post.author }} </p>
	</div>
	<div class="col-sm-2 col-lg-3"></div>
</div>
{% endfor %} 
{% else %}
<div class="post_container row">
	<p class="post_title">{{ post.author }} hasn't written any posts yet.</p>
</div>
{% endif %}

mysite/blogapp/templates/blog/home_navbar.html
<div class="navbar col-xs-12">
	<span class="nav-text">filter:</span> <button type="button" id="author_filter" class="btn btn-primary" data-toggle="modal" data-target="#filter-modal">
		authors
	</button>
	<div id="filter_panel">
		current filters:
		<div id="current_filters"></div>
	</div>
</div>

mysite/blogapp/templates/blog/post_list.html
{% if object_list %}
{% for post in object_list %} 
<div class="post_container row">
	<div class="col-sm-2"></div>
	<div class="post_date_container col-sm-2">
		<div id="eqpost-{{ post.id }}" class="post_title_equalizer"></div>
		<p class="post_date">{{ post.pub_date|date:"DATE_FORMAT" }}</p>
	</div>
	<div class="post col-sm-6 col-lg-5">
		<a href="#" id="post-{{ post.id }}" class="post_title">{{ post.title }}</a>
		<div class="post_content">{{ post.content|linebreaks }}</div>
		<p>author: {{ post.author }} </p>
	</div>
	<div class="col-sm-2 col-lg-3"></div>
</div>
{% endfor %} 
{% else %}
	<p>There are no posts.</p>
{% endif %}