mysite/blogapp/urls.py
from django.urls import include, path, re_path
from django.contrib import admin
from . import views

app_name = 'blogapp'
urlpatterns = [
	# project homepage, ex: /blog/
	path('', views.blogHome, name='blogHome'),
]

urlpatterns += [
	# page to create an account
	path('accounts/new_account/', views.CreateAccountView.as_view(), name='create_account'),
	re_path(r'^profile/$', views.UserProfileView.as_view(), name='user_profile'),
]

urlpatterns += [
	re_path(r'^posts$', views.getPosts, name='get_posts'),
	re_path(r'^authors$', views.getAuthors, name='get_authors'),
	path('post_list/', views.postList.as_view(), name='post_list'),
	path('create_post/', views.BlogPostCreate.as_view(), name='create_post'),
	path('post/<int:pk>/', views.PostDetail.as_view(), name='post_detail'),
	path('post/<int:pk>/edit/', views.BlogPostEdit.as_view(), name='edit_post'),
	path('post/<int:pk>/delete/', views.BlogPostDelete.as_view(), name='delete_post'),
	re_path(r'^filtered_posts$', views.FilterListView.as_view(), name='filter_list'),
]

mysite/mysite/urls.py
from django.contrib import admin
from django.urls import include, path
from blogapp import views
from django.views.generic import RedirectView

urlpatterns = [
	path('', views.blogHome, name='blogHome'),
	path('blogapp/', include('blogapp.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
	path('resume/',RedirectView.as_view(url='http://rebeccakempe.com/static/blog/Kempe_Resume_2018.pdf'))
  ]

mysite/blogapp/models.py
from django.db import models
from django.db.models.signals import post_save
from django.core.cache import cache
from django.contrib.auth.models import User
from django.urls import reverse_lazy, reverse

from django.utils import timezone

class Author(models.Model):
	user = models.ForeignKey(User, null=False, on_delete=models.CASCADE, editable=False)
	name = models.CharField(max_length=200)
	
	def __str__(self):
		return self.name
	
	def to_dict(self):
		return {
			'name': self.name,
		}

class BlogPost(models.Model):
	title = models.CharField(max_length=200)
	pub_date = models.DateField(auto_now_add=True)
	pub_time = models.TimeField(auto_now_add=True)
	last_edit_date = models.DateTimeField(auto_now=True)
	author = models.ForeignKey(Author, null=True, on_delete=models.SET_NULL, editable=False)
	content = models.TextField(null=True)
	
		
	def __str__(self):
		return self.title
	
	def get_absolute_url(self):
		return reverse('blogapp:blog/post_detail', kwargs={ 'pk' : self.pk })

	def to_dict(self):
		pub_time = str(self.pub_time)
		pub_date = str(self.pub_date)
		last_edit_date = str(self.last_edit_date)
		author = str(self.author)

		return {
			'id': self.id,
			'title': self.title,
			'pub_date': pub_date,
			'pub_time': pub_time,
			'last_edit_date': last_edit_date,
			'author': author,
			'content': self.content
		}
		
	class Meta:
		ordering = ['pub_date', 'pub_time']

mysite/blogapp/forms.py
from django import forms
from django.forms import ModelForm, widgets, Textarea

from blogapp.models import *

from django.contrib import messages
from django.core.exceptions import NON_FIELD_ERRORS
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm

from django.utils.translation import gettext_lazy as _


class CreateUserForm(UserCreationForm):
	email = forms.EmailField(required=True)
	
	class Meta:
		model = User
		fields = ('username','email','password1','password2')
		
	def save(self, commit=True):
		user = super(CreateUserForm, self).save(commit=False)
		user.email = self.cleaned_data['email']
		user.save()
		
		user_id = user.id
		author = Author.objects.create(user=user, name=user.username)
		
		return user
        	
class CreatePostForm(ModelForm):
	
	def __init__(self, *args, **kwargs):
		super(CreatePostForm, self).__init__(*args, **kwargs)
		self.fields['title'].widget.attrs = {
			'class': 'title_entry'
		}
		self.fields['content'].widget.attrs = {
			'class': 'post_content_entry'
		}
	
	class Meta:
		model = BlogPost
		fields = ('title','content')
		
	        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        

mysite/blogapp/views.py
# resources for browser navigation and webpage rendering
from django.http import HttpResponse, HttpResponseRedirect, JsonResponse
from django.shortcuts import render, get_object_or_404
from django.utils.html import escape
from django.urls import reverse_lazy, reverse

# views used in this file
from django.views import View
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.views.generic.detail import DetailView
from django.views.generic import ListView
from django.views.generic.base import TemplateView

# authentication and login resources
from django.contrib.auth import login, logout, authenticate
from django.contrib.auth.mixins import LoginRequiredMixin

# forms used in this file
from blogapp.forms import CreateUserForm, CreatePostForm

# models used in this file
from django.contrib.auth.models import User
from blogapp.models import *

import json




# INDEX  VIEW
# ===========

def blogHome(request):
	
	return render(
		request,
		'index.html',
		{
		}
	)

def getPosts(request):
	format = 'default'
	info_type = ''
	filter_string = None
	posts = []
	posts_json = []
	post_ids = []
	json_return = []
	new_posts = []
	no_new_posts = 0
	
	format = _clean(request, 'format', 'default')
	filter_string = _clean(request, 'filter')
	info_type = _clean(request, 'info_type')

	posts = BlogPost.objects.filter()
	
	if info_type == 'ids':
		for post in posts:
			post_ids.append(post.id)
		json_return = post_ids
	
	if info_type == 'update_ids':
		current_post_ids = request.GET.getlist('current_post_ids[]', [])
		current_post_ids = [json.loads(item) for item in current_post_ids]
		for post in posts:
			post_ids.append(post.id)
		if post_ids == current_post_ids:
			json_return = ['no new posts']
		else:
			for post in posts:
				if post.id not in current_post_ids:
					new_posts.append(post.to_dict())
					no_new_posts += 1
			json_return = no_new_posts
		
	return HttpResponse(
		json.dumps(json_return),
		content_type='application/json'
	 )

def getAuthors(request):
	format = 'default'
	filter_string = None
	authors = []
	authorslist = []
	
	format = _clean(request, 'format', 'default')
	filter_string = _clean(request, 'filter')
	
	authors = Author.objects.all()
		
	for author in authors:
		authorslist.append(
			[
				"<div><a href='javascript:filter(\"author\", " + str(author.id) + ", \"" + author.name + "\");'>" + author.name + "</a></div>"
			]
		)
	
	return HttpResponse(
		json.dumps(authorslist),
		content_type='application/json'
	 )

class postList(ListView):
	model = BlogPost
	template_name = 'blog/post_list.html'
	
	def get_queryset(self):
		qs = super().get_queryset()
		return BlogPost.objects.all().order_by('-pub_date', '-pub_time')
	
	def get_context_data(self, **kwargs):
		context = super().get_context_data(**kwargs)
		return context

class FilterListView(ListView):
	model = BlogPost
	template_name = 'blog/filter_list.html'
	format = 'default'
	filter_string = None
	filtered_posts = []
	
	def get_queryset(self):
		format = _clean(self.request, 'format', 'default')
		filter_string = _clean(self.request, 'filter')
		
		if filter_string:
			filters = filter_string.split(",")
			for f in filters:
				f_parts = f.split("_")
				if len(f_parts) == 2:
					filter_type = f_parts[0]
					filter_id = f_parts[1]
					if filter_type == "author":
						filtered_posts = BlogPost.objects.filter(author=filter_id)
# 						return BlogPost.objects.filter(author__username__contains=self.kwargs['author']).order_by('-pub_date')
		qs = super(FilterListView, self).get_queryset()
		return filtered_posts.order_by('-pub_date')


# USER ACCOUNT VIEWS
# ==================

class CreateAccountView(View):
	form_class = CreateUserForm
	initial = { 'key' : 'value'}
	template_name = 'registration/new_account.html'
	
	def get(self, request):
		form = self.form_class(initial=self.initial)
		if request.user.is_authenticated:
			#TODO Give user option to logout or return to profile
			return HttpResponse("You are already logged in.")
		return render(request, self.template_name, { 'form' : form })
	
	def post(self, request):
		form = self.form_class(request.POST)
		if form.is_valid():
			form.save()
			return HttpResponse('Account created. <a class="btn blue_btn" href="/accounts/login/">login</a>')
		else:
			return HttpResponse('An error has occurred. <a class="btn blue_btn" href="/blog/">Home</a>' )

class UserProfileView(LoginRequiredMixin, ListView):
	model = BlogPost
	template_name = 'profile.html'
	
	def get_queryset(self):
		qs = super(UserProfileView, self).get_queryset()
		user=self.request.user
		id = user.id
		return qs.filter(author__user=id).order_by('-pub_date')



# BLOG POST VIEWS
# ===============

class PostDetail(DetailView):
	model = BlogPost

class BlogPostCreate(LoginRequiredMixin, CreateView):
	template_name = 'blog/create_post.html'
	form_class = CreatePostForm
	initial = { 'key' : 'value'}
	
	def get(self, request):
		form = self.form_class(initial=self.initial)
		return render(request, self.template_name, { 'form' : form })
	
	def form_valid(self, form):
		author = Author.objects.get(user_id=self.request.user.id)
		form.instance.author = author
		return super().form_valid(form)
		if form.is_valid():
			form.save()

class BlogPostEdit(LoginRequiredMixin, UpdateView):
	model = BlogPost
	fields = ('title', 'content')
	template_name = 'edit_post.html'
	
	def get_queryset(self):
		qs = super(BlogPostEdit, self).get_queryset()
		return qs.filter(author=self.request.user)
		
	def form_valid(self, form):
		form.instance.last_edit_date = now
		return super().form_valid(form)
		if form.is_valid():
			form.save()
	
class BlogPostDelete(LoginRequiredMixin, DeleteView):
	model = BlogPost
	template_name = 'delete_post.html'
	
	def get_queryset(self):
		qs = super(BlogPostDelete, self).get_queryset()
		return qs.filter(author=self.request.user)
	success_url='/blog/'

def _clean(request, param, default='', method='GET'):
	clean_value = None

	if method == 'GET':
		clean_value = escape(request.GET.get(param, default))
	elif method == 'POST':
		clean_value = escape(request.POST.get(param, default))

	return clean_value
		
		
# RESUME VIEW
# =============


def resume(request):
	return HttpResponseRedirect("../blog/static/blog/Kempe_Resume_2018.pdf")
	
		
		
		
		
		
		
		

mysite/blogapp/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
	{% block title %}<title>FS Blog</title>{% endblock %}
	{% load static %}
	
	<!-- Latest compiled and minified CSS -->
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
	<!-- jQuery library -->
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
	<!-- Latest compiled JavaScript -->
	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
	
	<script src="{% static 'blog/jquery.js' %}" type="text/javascript"></script>
	
	<!-- stylesheets -->
	<link rel="stylesheet" type="text/css" href="{% static 'blog/style.css' %}" />
	
	<meta name="viewport" content="width=device-width, initial-scale=1">
</head>
<body>
	<div class="container-fluid">
		{% block nav %}
			
		{% endblock %}
		{% block content %}<!-- default content text (typically empty) -->{% endblock %}
	</div>
</body>
</html>

mysite/blogapp/templates/index.html
{% extends 'blog/blog_base.html' %}
{% load static %}
{% csrf_token %}


{% block title %}
	<title>FS Blog Home</title>
{% endblock %}

{% block modals %}
	<div id="filter-modal" class="modal fade" tabindex="-1" role="dialog">
		<div class="modal-dialog" role="document">
			<div class="modal-content">
				<div class="modal-header">
					<button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
					<h3 class="modal-title">filter</h3>
				</div>
				<div class="modal-body">
					<ul class="nav nav-tabs" role="tablist">
						<li role="presentation" class="active">
							<a href="#authors" aria-controls="people" role="tab" data-toggle="tab">authors</a>
						</li>
					</ul>
				</div>
				<div class="tab-content wbhb-tab-pane">
					<div role="tabpanel" class="tab-pane active" id="authors">
						<div id="author-table" style="width: 100%;">
							
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
{% endblock %}

{% block content %}
	<div id="home_splash" class="row">
		<div id="blog_videoScribe_container" class="col-md-6">
			<video muted playsinline autoplay preload="auto" id="blog_videoScribe">
				<source src="{% static 'blog/blog_videoScribing.mp4' %}" type="video/mp4">
			</video>
		</div>
		<div id="homesplash_right" class="col-md-6">
			<div id="homesplash_text_container">
				<div id="homesplash_text_buttons">
					<div class="homesplash_text">a meta commentary on the creation thereof</div>
					<div id="login_btn_container">
						<a href="{% url 'blogapp:create_account' %}" id="join_btn" class="btn blue_btn">join</a>
						<a href="{% url 'login' %}" id="login_btn" class="btn">login</a>
					</div>
				</div>
			</div>
		</div>
	</div>

	{% include "blog/home_navbar.html" %}
	<div id="home_content">
		<div class="new_posts row">
			<div class="col-sm-2"></div>
			<button type="button" value="Refresh Page" onClick="window.location.reload()" id="new_posts" class="col-sm-8 col-lg-7 btn btn-primary">
			</button>
			<div class="col-sm-2 col-lg-3"></div>
		</div>
		<div id="posts" class="row">
		</div>
	</div>
{% endblock %}


{% block javascript %}
	<script type="text/javascript">
		var filters = [];
		var info_type = ''
		var data = null
		var post_ids = []
		var date = new Date();
		
		var source_url = 'blogapp/posts?format=default&info_type='
		var authors_url = 'blogapp/authors?format=default&filter='
		var filter_url = 'blogapp/filtered_posts?format=default&filter='
		
		$(document).ready(function(){
			$('#homesplash_text_buttons').hide(0);
			getFilterTable();
			var width = $(window).width(); // New width
			if (width < 1100 ) {
				$('#blog_videoScribe_container').removeClass('col-md-6').addClass('col-md-7');
				$('#homesplash_right').removeClass('col-md-6').addClass('col-md-5');
			}
			info_type = 'posts';
			url = 'blogapp/post_list/'
			successFunction = function(data){
				sizeTitleEqualizerSpace(data, '#posts');
				getIDs();
			}
			ajaxCall(url, 'GET', null, processData=false, contentType=false, successFunction);
			
			function getFilterTable() {
				url = authors_url.replace('&filter=', '');
				successFunction = function(response) {
					for (var x = 0; x < response.length; x ++) {
						author = response[x][0]
						$('#author-table').append(author)
					}
				}
				ajaxCall(url, 'GET', null, processData=true, contentType='application/json', successFunction);
			}
		});
			
		$(window).bind('load', function(){
			$('#homesplash_text_buttons').hide(0).delay(9800).fadeIn();
		});
		
		$(window).resize(function() {
			$(window).height(); // New height
			var width = $(window).width(); // New width
			if (width <= 1100 ) {
				$('#blog_videoScribe_container').removeClass('col-md-6').addClass('col-md-7');
				$('#homesplash_right').removeClass('col-md-6').addClass('col-md-5');
			} else {
				$('#blog_videoScribe_container').removeClass('col-md-7').addClass('col-md-6');
				$('#homesplash_right').removeClass('col-md-5').addClass('col-md-6');
			};
			if (data != null) {
				sizeTitleEqualizerSpace(data, '#posts');
			}
		});
		

	</script>
{% endblock %}

mysite/blogapp/templates/index_old.html
{% extends 'base.html' %}


	
{% block content %}
	<div id="index_page" class="container-fluid">
	<script>
		var ajax_call = function() {
			$.get("http://45.79.145.31:8000/", function(data, status){
				$("html").html(data);
		    });
		};
		
		var interval = 1000 * 60 * 1;
		
		setInterval(ajax_call, interval);
		
		
	</script>
	
	{% csrf_token %}
	
	<div id="home_splash" class="row">
		{% load static %}
		<div id="blog_videoScribe_container" class="col-md-6">
			<video muted playsinline autoplay preload="auto" id="blog_videoScribe">
				<source src="{% static 'blog/blog_videoScribing.mp4' %}" type="video/mp4">
			</video>
		</div>
		<div id="homesplash_right" class="col-md-6">
			<div id="homesplash_text_container">
				<div id="homesplash_text-buttons">
					<div class="homesplash_text">a meta commentary on the creation thereof</div>
					<div id="login_btn_container">
						<a href="{% url 'blog:create_account' %}" id="join_btn" class="btn blue_btn">join</a>
			<!-- 			<div id="homesplash_account">Already have an account?</div> -->
						<a href="{% url 'login' %}" id="login_btn" class="btn">login</a>
					</div>
				</div>
			</div>
		</div>
	</div>
	<div id="home_content">
		<div class="navbar col-xs-12">
			<a href="{% url 'blog:user_list' %}">authors</a>
			|<a href="{% url 'blog:create_post' %}"> + post</a>
		</div>
		<div class="new_posts">
		</div>
		{% if blogpost_list %}
		{% for post in blogpost_list %} 
		<div class="post_container row">
			<div class="col-sm-2"></div>
			<div class="post_date_container col-sm-2">
		        <div class="post_title_equalizer"></div>
				<p class="post_date">{{ post.pub_date|date:"DATE_FORMAT" }}</p>
	        </div>
	        <div class="post col-sm-6 col-lg-4">
		        <a href="{% url 'blog:post_detail' post.id %}" class="post_title">{{ post.title }}</a>
		        <div class="post_content">{{ post.content|linebreaks }}</div>
		        <p>author: {{ post.author }} </p>
	        </div>
	        <div class="col-sm-2 col-lg-4"></div>
	    </div>
	    {% endfor %} 
	    {% else %}
	      <p>There are no posts.</p>
	    {% endif %}
		
	</div>
	
</div>	
{% endblock %}

mysite/blogapp/templates/profile.html
{% extends 'blog/blog_base.html' %}
{% load static %}

{% csrf_token %}

{% block nav %}
	<div class="navbar col-xs-12">
		<a href="{% url 'index' %}"><img class="home_arrow" alt="home" src="{% static 'blog/home_arrow.png/' %}"></a>
		<a href=""> {{ user.username }} </a>
		|
		<a href="{% url 'blog:create_post' %}"> + post</a>
	</div>
{% endblock %}

{% block content %}

<div id="post_detail">
	{% if blogpost_list %}
	{% for post in blogpost_list %} 
		<div class="post_container row">
			<div class="col-sm-2"></div>
			<div class="post_date_container col-sm-2">
		        <div class="post_title_equalizer"></div>
				<p class="post_date">{{ post.pub_date|date:"DATE_FORMAT" }}</p>
				<p class="edit_date">last edited: {{ post.last_edit_date }}</p>
	        </div>
	        <div class="post col-sm-6 col-lg-4">
		        <a href="{% url 'blog:post_detail' post.id %}" class="post_title">{{ post.title }}</a>
		        <div class="post_content">{{ post.content|linebreaks }}</div>
		        <div class="postModifier_glyphs">
			        <a href="{% url 'blog:delete_post' post.id %}"><img id="delete_glyph" alt="delete post" src="{% static 'blog/delete.png/' %}"></a>
			        <a href="{% url 'blog:edit_post' post.id %}"><img id="edit_glyph" alt="edit post" src="{% static 'blog/edit.png/' %}"></a>
		        </div>
	        </div>
	        <div class="col-sm-2 col-lg-4"></div>
	    </div>
	    {% endfor %} 
    {% else %}
      <p>You haven't written any posts yet.</p>
    {% endif %} 
	
</div>


{% endblock %}

mysite/blogapp/templates/resume.html
<!DOCTYPE html>
<html lang="en">
<head>
	{% block title %}<title>FS Blog</title>{% endblock %}
	{% load static %}
	
	<!-- Latest compiled and minified CSS -->
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
	<!-- jQuery library -->
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
	<!-- Latest compiled JavaScript -->
	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
	
	<script src="{% static 'blog/jquery.js' %}" type="text/javascript"></script>
	
	<!-- stylesheets -->
	<link rel="stylesheet" type="text/css" href="{% static 'blog/style.css' %}" />
	
	<meta name="viewport" content="width=device-width, initial-scale=1">
</head>
<body>
{% load static %}
<div class="container-fluid" >
	<embed class="col-xs-12" src="{% static 'blog/Kempe_Resume_2018.pdf' %}" height="100%" />
</div>

</body>
</html>

mysite/blogapp/templates/user_list.html
{% extends 'base.html' %}

{% load static %}
{% block nav %}
	<div class="navbar col-xs-12">
		<a href="{% url 'index' %}"><img class="home_arrow" alt="home" src="{% static 'blog/home_arrow.png/' %}"></a>
		|
		<a href="{% url 'blog:create_post' %}"> + post</a>
	</div>
{% endblock %}

{% block content %}

{% csrf_token %}

<div class="container author_list">
	<p class="post_title">Authors:</p>
	{% if user_list %}
	{% for user in user_list %}
		<div>
		<a class="post_author" href="{% url 'blog:author_profile' user.username %}">
		{{ user.username }}
		</a>
		</div>
	{% endfor %}
	{% endif %}

</div>
{% endblock %}